#!/usr/bin/env bash

PERCENT=$(cat /sys/class/power_supply/BAT1/capacity)
STATUS=$(cat /sys/class/power_supply/BAT1/status)

# Selección de color e ícono según el nivel de batería
if (( PERCENT <= 20 )); then
  ICON=" "
  COLOR="#ff0000"  # rojo
elif (( PERCENT <= 40 )); then
  ICON=" "
  COLOR="#ff9900"  # naranja
elif (( PERCENT <= 60 )); then
  ICON=" "
  COLOR="#ffff00"  # amarillo
elif (( PERCENT <= 80 )); then
  ICON=" "
  COLOR="#99ff66"  # verde claro
else
  ICON=" "
  COLOR="#00ff00"  # verde
fi

#Estado de conexion a corriente o no
ICON_STR=$([[ $STATUS == "Charging" ]] && echo " " || echo "$ICON")
COLOR=$([[ $STATUS == "Charging" ]] && echo "#fff"  || echo "$COLOR")
#
# Imprimir usando Pango markup
echo "<span color='$COLOR'>$ICON_STR${PERCENT}%</span>"
